# 设置本镜像需要使用的基础镜像
FROM openjdk:8

#ENV APP_PATH = /home/toolset
#
#WORKDIR $APP_PATH

# 把jar包添加到镜像中
ADD toolset-0.0.1-SNAPSHOT.jar /home/toolset/toolset-0.0.1-SNAPSHOT.jar


# 把nginx配置文件添加到镜像中
ADD nginx.conf /home/toolset/nginx.conf
ADD start.sh /home/toolset/start.sh


# 把前端zip包添加到镜像中
ADD dist.zip /home/toolset/dist.zip
# 把脚本包添加到镜像中
ADD scripts.zip /home/scripts.zip


# 把Python-2.7.10.tgz包添加到镜像中
ADD Python-2.7.10.tgz /tmp
# 把jdk-11.0.19_linux-x64_bin.tar.gz包添加到镜像中
ADD jdk-11.0.19_linux-x64_bin.tar.gz /tmp


# 替换阿里源
RUN cp /etc/apt/sources.list /etc/apt/sources.list.bak
RUN echo "deb https://mirrors.aliyun.com/debian stable main contrib non-free" > /etc/apt/sources.list
RUN echo "deb https://mirrors.aliyun.com/debian stable-updates main contrib non-free" >> /etc/apt/sources.list
RUN apt update
# 安装nmap
RUN apt install nmap -y
# 安装nginx
RUN apt install nginx -y
# 安装make
RUN apt install make
RUN apt install gcc -y
# 安装zlib*
RUN apt install zlib*


# 安装python2
# RUN tar -zxvf Python-2.7.10.tgz #ADD会自动解压缩
WORKDIR /tmp/Python-2.7.10
ADD Setup.dist /tmp/Python-2.7.10/Modules
RUN ./configure --prefix=/usr/local/python2
RUN make
RUN make install

# 安装JDK11
# RUN tar -zxvf jdk-11.0.19_linux-x64_bin.tar.gz  #ADD会自动解压缩

# 命令映射
RUN update-alternatives --install    /usr/bin/python2    python2    /usr/local/python2/bin/python   200
RUN update-alternatives --install    /usr/bin/java11    java11    /tmp/jdk-11.0.19/bin/java   400
RUN update-alternatives --install    /usr/bin/java8    java8    /usr/local/openjdk-8/bin/java   300


# 下载python2的pip
WORKDIR /tmp
RUN curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py
RUN python2 get-pip.py -i http://pypi.douban.com/simple --trusted-host pypi.douban.com


#解压
WORKDIR /home
RUN unzip scripts.zip
RUN rm -f scripts.zip

WORKDIR /home/toolset
RUN unzip dist.zip
RUN rm -f dist.zip

#修改nginx配置文件
RUN mv /etc/nginx/nginx.conf /etc/nginx/nginx.conf.back
RUN mv nginx.conf /etc/nginx/nginx.conf


#下载工具包依赖
RUN apt install python3-requests -y
RUN apt install python3-scapy -y
RUN python2 -m pip install requests -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com

# 设置时区
RUN /bin/cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' >/etc/timezone

# 镜像暴露的端口
EXPOSE 9090
EXPOSE 80

# 容器启动命令
#ENTRYPOINT ["sh", "-c", "echo ${APP_PATH}"]
#ENTRYPOINT ["java", "-jar", "/home/toolset/toolset-0.0.1-SNAPSHOT.jar", "--spring.profiles.active=test"]
ENTRYPOINT ["sh", "start.sh"]